# Generated by Django 5.0.6 on 2026-05-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['name'], 'verbose_name': 'Chuyên khoa', 'verbose_name_plural': 'Chuyên khoa'},
        ),
    ]
