# Generated by Django 5.0.6 on 2026-05-21 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_prescription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã thuốc')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thuốc')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('unit', models.CharField(default='viên', max_length=50, verbose_name='Đơn vị tính')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thuốc trong kho',
                'verbose_name_plural': 'Thuốc trong kho',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDispensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian phát')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('pharmacist', models.ForeignKey(limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dược sĩ')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispensation', to='bookings.prescription', verbose_name='Đơn thuốc')),
            ],
            options={
                'verbose_name': 'Phiếu phát thuốc',
                'verbose_name_plural': 'Phiếu phát thuốc',
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDispensationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá lúc phát')),
                ('dispensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescriptiondispensation', verbose_name='Phiếu phát thuốc')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Chi tiết thuốc phát',
                'verbose_name_plural': 'Chi tiết thuốc phát',
            },
        ),
    ]
