# Generated by Django 5.0.6 on 2026-05-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleVerification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Hồ sơ", "verbose_name_plural": "Hồ sơ"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Người dùng",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                max_length=10,
            ),
        ),
    ]
