# Generated by Django 5.0.6 on 2026-05-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_googleverification_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="provider",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
