# Generated by Django 5.0.6 on 2026-05-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_user_options_and_more'),
        ('accounts', '0003_profile_avatar_url_user_provider'),
    ]

    operations = [
    ]
