# Generated by Django 5.0.6 on 2026-05-25 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_20260523_1512"),
        ("core", "0005_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="core.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("pharmacist", "Pharmacist"),
                    ("dept_doctor", "Department Doctor"),
                ],
                default="patient",
                error_messages={"required": "Role must be provided"},
                max_length=20,
            ),
        ),
    ]
