# Generated by Django 5.0.6 on 2026-05-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('nurse', 'Điều dưỡng'), ('receptionist', 'Tiếp tân'), ('pharmacist', 'Dược sĩ'), ('admin', 'Quản trị viên')], default='patient', error_messages={'required': 'Role must be provided'}, max_length=20),
        ),
    ]
