# Generated by Django 5.0.6 on 2026-05-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khám')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Triệu chứng')),
                ('initial_diagnosis', models.TextField(blank=True, null=True, verbose_name='Chẩn đoán sơ bộ')),
                ('final_diagnosis', models.TextField(blank=True, null=True, verbose_name='Chẩn đoán xác định (ICD-10)')),
                ('treatment_plan', models.TextField(blank=True, null=True, verbose_name='Hướng điều trị')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Bệnh án',
                'verbose_name_plural': 'Bệnh án',
                'db_table': 'medical_records',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255, verbose_name='Tên thuốc')),
                ('active_ingredient', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hoạt chất')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đơn vị tính')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá (VNĐ)')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Danh mục thuốc',
                'db_table': 'medicines',
                'ordering': ['medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='Tên vai trò')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Vai trò',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
            ],
            options={
                'verbose_name': 'Danh mục dịch vụ',
                'verbose_name_plural': 'Danh mục dịch vụ',
                'db_table': 'service_categories',
            },
        ),
        migrations.CreateModel(
            name='ClinicPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày kê đơn')),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_prescription', to='clinic.medicalrecord', verbose_name='Bệnh án')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=20, unique=True, verbose_name='Mã bệnh nhân')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True, verbose_name='Giới tính')),
                ('birthday', models.DateField(verbose_name='Ngày sinh')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nhóm máu')),
                ('allergy_history', models.TextField(blank=True, null=True, verbose_name='Tiền sử dị ứng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản Doccure (nếu có)')),
            ],
            options={
                'verbose_name': 'Bệnh nhân',
                'verbose_name_plural': 'Bệnh nhân',
                'db_table': 'clinic_patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='clinic.patient', verbose_name='Bệnh nhân'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tổng tiền (VNĐ)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Giảm giá (VNĐ)')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Thực thu (VNĐ)')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('partially_paid', 'Thanh toán một phần')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày lập hóa đơn')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinic.medicalrecord', verbose_name='Bệnh án')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinic.patient', verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản'), ('credit_card', 'Thẻ ngân hàng')], max_length=20, null=True, verbose_name='Phương thức thanh toán')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền (VNĐ)')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm thanh toán')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clinic.invoice', verbose_name='Hóa đơn')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Giao dịch thanh toán',
                'db_table': 'payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('dosage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Liều dùng')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Cách dùng')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='clinic.medicine', verbose_name='Thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.clinicprescription', verbose_name='Đơn thuốc')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn thuốc',
                'verbose_name_plural': 'Chi tiết đơn thuốc',
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá (VNĐ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='clinic.servicecategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chuyên khoa')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('certificate_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chứng chỉ hành nghề')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên',
                'verbose_name_plural': 'Hồ sơ nhân viên',
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('result_text', models.TextField(blank=True, null=True, verbose_name='Kết quả (văn bản)')),
                ('result_json', models.JSONField(blank=True, null=True, verbose_name='Kết quả (JSON / file đính kèm)')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm thực hiện')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='clinic.medicalrecord', verbose_name='Bệnh án')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='clinic.service', verbose_name='Dịch vụ')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_service_orders', to='clinic.staffprofile', verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Phiếu chỉ định dịch vụ',
                'verbose_name_plural': 'Phiếu chỉ định dịch vụ',
                'db_table': 'service_orders',
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='clinic.staffprofile', verbose_name='Bác sĩ'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Ngày & giờ hẹn')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do khám')),
                ('status', models.CharField(choices=[('scheduled', 'Chờ khám'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.patient', verbose_name='Bệnh nhân')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.staffprofile', verbose_name='Bác sĩ phụ trách')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'db_table': 'clinic_appointments',
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cân nặng (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chiều cao (cm)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Thân nhiệt (°C)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Nhịp tim (lần/phút)')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True, verbose_name='Huyết áp (mmHg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm ghi')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='clinic.appointment', verbose_name='Lịch hẹn')),
            ],
            options={
                'verbose_name': 'Chỉ số sinh tồn',
                'verbose_name_plural': 'Chỉ số sinh tồn',
                'db_table': 'vital_signs',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='clinic.role', verbose_name='Vai trò')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Phân quyền',
                'verbose_name_plural': 'Phân quyền',
                'db_table': 'user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
