# Generated by Django 5.0.6 on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_prescription'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        # --- Xoá Role và UserRole (phân quyền dùng accounts.User.role) ---
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        # --- Thêm field booking vào Appointment ---
        migrations.AddField(
            model_name='appointment',
            name='booking',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='clinic_appointment',
                to='bookings.booking',
                verbose_name='Đặt lịch online (nếu có)',
            ),
        ),
        # --- Thêm field booking_prescription vào ClinicPrescription ---
        migrations.AddField(
            model_name='clinicprescription',
            name='booking_prescription',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='clinic_prescription_link',
                to='bookings.prescription',
                verbose_name='Đơn thuốc online (nếu có)',
            ),
        ),
    ]
