# Generated by Django 5.0.6 on 2026-05-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-appointment_date', '-appointment_time'], 'verbose_name': 'Lịch khám', 'verbose_name_plural': 'Lịch khám'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn thuốc', 'verbose_name_plural': 'Đơn thuốc'},
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ phát thuốc'), ('dispensed', 'Đã phát thuốc')], default='pending', max_length=20),
        ),
    ]
