# Generated by Django 5.0.6 on 2026-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_referral_result_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="reason",
            field=models.TextField(blank=True),
        ),
    ]
