# Generated by Django 5.0.6 on 2026-05-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_referral_reason"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionMedicine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Số lượng/ngày"
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Liều dùng"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tần suất"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Thời gian dùng",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Hướng dẫn"),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="bookings.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thuốc trong đơn",
                "verbose_name_plural": "Thuốc trong đơn",
            },
        ),
    ]
