# Generated by Django 5.0.6 on 2026-05-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_experience_from_year_alter_experience_to_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Bằng cấp', 'verbose_name_plural': 'Bằng cấp'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Kinh nghiệm', 'verbose_name_plural': 'Kinh nghiệm'},
        ),
        migrations.AlterModelOptions(
            name='friday',
            options={'verbose_name': 'Thứ Sáu', 'verbose_name_plural': 'Thứ Sáu'},
        ),
        migrations.AlterModelOptions(
            name='monday',
            options={'verbose_name': 'Thứ Hai', 'verbose_name_plural': 'Thứ Hai'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá bác sĩ', 'verbose_name_plural': 'Đánh giá bác sĩ'},
        ),
        migrations.AlterModelOptions(
            name='saturday',
            options={'verbose_name': 'Thứ Bảy', 'verbose_name_plural': 'Thứ Bảy'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Chuyên khoa', 'verbose_name_plural': 'Chuyên khoa'},
        ),
        migrations.AlterModelOptions(
            name='sunday',
            options={'verbose_name': 'Chủ Nhật', 'verbose_name_plural': 'Chủ Nhật'},
        ),
        migrations.AlterModelOptions(
            name='thursday',
            options={'verbose_name': 'Thứ Năm', 'verbose_name_plural': 'Thứ Năm'},
        ),
        migrations.AlterModelOptions(
            name='timerange',
            options={'verbose_name': 'Khoảng thời gian', 'verbose_name_plural': 'Khoảng thời gian'},
        ),
        migrations.AlterModelOptions(
            name='tuesday',
            options={'verbose_name': 'Thứ Ba', 'verbose_name_plural': 'Thứ Ba'},
        ),
        migrations.AlterModelOptions(
            name='wednesday',
            options={'verbose_name': 'Thứ Tư', 'verbose_name_plural': 'Thứ Tư'},
        ),
    ]
